ARCH: convtasnet
FS: 16000
TRAINING:
  CRITERION: SNR
  CUDA: true
  EARLY_STOP:
    PATIENCE: 10
    TOGGLE: false
  CONVERGENCE:
    WINDOW: 10
    THRESHOLD: 1.0e-6
    TOGGLE: false
  EPOCHS: 150
  LEARNING_RATE: 1.0e-3
  WORKERS: 4
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0
  PATH: data/processed/train/foo/
  SEED: 0
  VAL_SIZE: 0.1
  PRELOAD: false
  GRAD_CLIP: 5.0  # 0.0 to disable
  SEGMENT_LENGTH: 4.0  # 0.0 to disable
  BATCH_SAMPLER:
    WHICH: bucket
    BATCH_SIZE: 128.0
    NUM_BUCKETS: 10
    DYNAMIC: True
MODEL:
  ENCODER:
    FILTERS: 128  # 512
    FILTER_LENGTH: 32  # 16
  TCN:
    BOTTLENECK_CHANNELS: 128
    HIDDEN_CHANNELS: 256  # 512
    SKIP_CHANNELS: 128
    KERNEL_SIZE: 3
    LAYERS: 7  # 8
    REPEATS: 2  # 3
  SOURCES:
    - foreground
    # - background
