ARCH: convtasnet
TRAINING:
  BATCH_SIZE: 1
  CRITERION: SISNR
  CUDA: true
  EARLY_STOP:
    PATIENCE: 10
    TOGGLE: false
  CONVERGENCE:
    WINDOW: 10
    THRESHOLD: 1.0e-6
    TOGGLE: false
  EPOCHS: 100
  LEARNING_RATE: 1.0e-3
  WORKERS: 4
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0
  PATH: data/processed/train/foo/
  SEED: 0
  VAL_SIZE: 0.1
  PRELOAD: false
  MIXED_PRECISION: false
  GRAD_CLIP: 5.0  # 0.0 to disable
MODEL:
  ENCODER:
    FILTERS: 512
    FILTER_LENGTH: 16
  TCN:
    BOTTLENECK_CHANNELS: 128
    HIDDEN_CHANNELS: 512
    SKIP_CHANNELS: 128
    KERNEL_SIZE: 3
    LAYERS: 8
    REPEATS: 3
    SOURCES: 2
