ARCH: dnn
FS: 16000
TRAINING:
  CRITERION: MSELoss
  CUDA: true
  EARLY_STOP:
    PATIENCE: 10
    TOGGLE: false
  CONVERGENCE:
    WINDOW: 10
    THRESHOLD: 1.0e-6
    TOGGLE: false
  EPOCHS: 100
  LEARNING_RATE: 1.0e-4
  WORKERS: 0
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0
  PATH: data/processed/train/foo/
  SEED: 0
  VAL_SIZE: 0.1
  PRELOAD: true
  GRAD_CLIP: 0.0  # 0.0 to disable
  SEGMENT_LENGTH: 4.0  # 0.0 to disable
  BATCH_SAMPLER:
    WHICH: bucket
    BATCH_SIZE: 16.0
    NUM_BUCKETS: 10
    SORTED: False
MODEL:
  BATCH_NORM:
    MOMENTUM: 0.1
    TOGGLE: false
  DROPOUT: 0.2  # 0.0 to disable
  HIDDEN_LAYERS: [1024, 1024]
  NORMALIZATION:
    TYPE: static
    GROUP: false
  FEATURES: !!set
    # ild: null
    # itd_ic: null
    # logpdf: null
    # logmfcc: null
    # cubicmfcc: null
    # pdf: null
    # pdfcc: null
    logfbe: null
  STFT:
    FRAME_LENGTH: 512
    HOP_LENGTH: 256
    WINDOW: hann
  MEL_FILTERS: 64
  DECIMATION: 2
  DCT_COEFF: 0
  STACKS: 5
  SCALE_RMS: false
