BATCH_SIZE: 1
CRITERION: MSELoss
CUDA: true
EARLY_STOP:
  PATIENCE: 0
  TOGGLE: false
CONVERGENCE:
  WINDOW: 10
  THRESHOLD: 1.0e-6
  TOGGLE: false
EPOCHS:
  100
LEARNING_RATE: 1.0e-4
WORKERS: 0
OPTIMIZER: Adam
WEIGHT_DECAY: 0.0
PATH: data/processed/train/foo/
SEED: 0
VAL_SPLIT: 0.1
